### ISSUE TITLE
RFE: Use new RT

### ISSUE THREAD

**Issue by funnelfiasco** [mscman/Officebuddysays#1]
Switch to using new RT support provided in TTYtter 1.2. This will allow the full tweet to be sent (e.g. not removing the searched hashtag) but may require some ensmartening to make sure it doesn't result in an endless loop.

**Comment by funnelfiasco** [comment]
Initial code modifications made to use newRT. The problem is that it only RTs tweets from accounts it follows. I don't know if it's a problem in our configuration or in the code used to request the RT. May have to inquire upstream.

**Comment by mscman** [comment]
Maybe you should fork & commit so people can see the changes. Hint hint.

**Comment by funnelfiasco** [comment]
Semi-working code branched into 1.1

**Comment by funnelfiasco** [comment]
1.1 has been merged into master.
